filter:
    excluded_paths:
        - 'tests/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php:
            version: 7.1.0
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage -c phpunit.xml'
                coverage:
                    file: 'coverage'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
