filter:
    excluded_paths:
        - 'tests/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php:
            version: 7.0.8
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage -c phpunit.xml'
                coverage:
                    file: 'coverage'
                    format: 'clover'
